[Task][66296] Create Home Screen
awesome-academy/ios_naitei_moviedb_020823 pull request #7
Opened 2023-08-09 09:21 UTC by saske999cz

## [Pull request title]
[Task][66296] Create Home Screen
### [Redmine link]
(https://edu-redmine.sun-asterisk.vn/issues/66296)
#### Screenshots (nếu có)
<img width="450" alt="Screenshot 2023-08-09 at 16 18 35" src="https://github.com/awesome-academy/ios_naitei_moviedb_020823/assets/83598304/a39e4e73-8c3c-4b3c-865c-8f2f41074c6c">
<img width="349" alt="Screenshot 2023-08-09 at 16 18 49" src="https://github.com/awesome-academy/ios_naitei_moviedb_020823/assets/83598304/a4b6df0f-17ef-4b70-a8bf-0ecdef35e8be">

2023-08-09 09:23 UTC, 2fng commented on MovieDB/Controller/HomeViewController.swift
> +class HomeViewController: UIViewController {
```suggestion
final class HomeViewController: UIViewController {
```

2023-08-09 09:28 UTC, 2fng requested changes

2023-08-09 09:28 UTC, 2fng commented on MovieDB/Controller/HomeViewController.swift
> +    @IBOutlet private weak var logo: UIImageView!
```suggestion
    @IBOutlet private weak var logoImageView: UIImageView!
```

2023-08-09 09:28 UTC, 2fng commented on MovieDB/Controller/HomeViewController.swift
> +    private var movies = [Movie]()
```suggestion
    @IBOutlet private weak var movieTableView: UITableView!
    
    private var movies = [Movie]()
```

2023-08-09 09:28 UTC, 2fng commented on MovieDB/Controller/HomeViewController.swift
> +
Em check lại swiftlint xem có chạy không nhé

2023-08-09 09:28 UTC, 2fng commented on MovieDB/Controller/HomeViewController.swift
> +
Tương tự như trên

2023-08-09 09:28 UTC, 2fng commented on MovieDB/Controller/HomeViewController.swift
> +extension HomeViewController: UITableViewDelegate, UITableViewDataSource {
Tách riêng 2 extension cho Delegate và DataSourcce nhé

2023-08-09 09:28 UTC, 2fng commented on MovieDB/Controller/HomeViewController.swift
> +        guard let cell = movieTableView.dequeueReusableCell(withIdentifier: "TableMovieCell", for: indexPath) as? TableMovieCell else { return TableMovieCell() }
Như project 1, em áp dụng ReusableCell cho các cell nhé

2023-08-09 09:28 UTC, 2fng commented on MovieDB/Controller/HomeViewController.swift
> +        return numOfMovies
```suggestion
        return movies.count
```

2023-08-09 09:28 UTC, 2fng commented on MovieDB/Controller/HomeViewController.swift
> +    }
```suggestion
```

2023-08-09 09:28 UTC, 2fng commented on MovieDB/Controller/HomeViewController.swift
> +    }
```suggestion
```

2023-08-09 09:28 UTC, 2fng commented on MovieDB/Controller/HomeViewController.swift
> +    }
hard code

2023-08-09 09:28 UTC, 2fng commented on MovieDB/View/CollectionMovieCell.swift
> +class CollectionMovieCell: UICollectionViewCell {
```suggestion
final class CollectionMovieCell: UICollectionViewCell {
```

2023-08-09 09:28 UTC, 2fng commented on MovieDB/View/CollectionMovieCell.swift
> +    @IBOutlet private weak var moviePoster: UIImageView!
```suggestion
    @IBOutlet private weak var posterImageView: UIImageView!
```

2023-08-09 09:28 UTC, 2fng commented on MovieDB/View/TableMovieCell.swift
> +class TableMovieCell: UITableViewCell {
```suggestion
final class TableMovieCell: UITableViewCell {
```

2023-08-09 09:28 UTC, 2fng commented on MovieDB/View/TableMovieCell.swift
> +        return numOfMovies
```suggestion
        return movies.count
```

2023-08-09 09:30 UTC, tuta-3205 commented on MovieDB/Controller/HomeViewController.swift
> +
@2fng 
Anh thấy cái ci tín chưa a =))))

2023-08-14 03:55 UTC, namtn-2711 commented on MovieDB/Constants/Sections.swift
> +}
Lạm dụng static quá e, chuyển qua enum nhé

2023-08-14 06:30 UTC, tunghs-1253 commented on MovieDB/Controller/HomeViewController.swift
> +    }
Không dùng xoá đi em

2023-08-14 06:31 UTC, namtn-2711 commented on MovieDB/Constants/Sections.swift
> +    }
enum để chia các case sao lại viết tnay e ơi

2023-08-14 06:34 UTC, namtn-2711 commented on MovieDB/Controller/HomeViewController.swift
> +        guard let cell = movieTableView.dequeueReusableCell(withIdentifier: "TableMovieCell", for: indexPath) as? TableMovieCell else { return TableMovieCell() }
TableMovieCell đọc ngượng mồm quá nhỉ e @tunghs-1253

2023-08-14 13:47 UTC, namtn-2711 commented on MovieDB/Constants/Sections.swift
> +}
```suggestion
enum HomeSections: CaseIterable {
    case trending
    case popular
    case topRated
    case discover
    
    func getTitle() -> String {
        switch self {
        case .trending:
            return "Trending"
        case .popular:
            return "Popular"
        case .topRated:
            return "Top Rated"
        case .discover:
            return "Discover"
        }
    }
}
```

2023-08-14 13:47 UTC, namtn-2711 commented on MovieDB/Controller/HomeViewController.swift
> +    private var sections = Sections.getAllTitles()
```suggestion
    private var sections = HomeSections.allCases
```

2023-08-14 13:47 UTC, namtn-2711 commented on MovieDB/Controller/HomeViewController.swift
> +        return sections[section]
```suggestion
        return sections[section].title
```

2023-08-15 02:28 UTC, tunghs-1253 approved these changes

2023-08-15 02:28 UTC, merged